# tests/integration/get-conversion-imagebasedFile.hurl
# Authenticated POST to /v1/fragments

POST http://localhost:8080/v1/fragments
# user1@email.com:password1
Authorization: Basic dXNlcjFAZW1haWwuY29tOnBhc3N3b3JkMQ==
Content-Type: image/jpeg
file,test.jpg;



HTTP/1.1 201
[Asserts]
header "Location" matches "^http:\/\/localhost:8080\/v1\/fragments\/[A-Za-z0-9_-]+$"
jsonpath "$.status" == "ok"
jsonpath "$.fragment.id" matches "^[A-Za-z0-9_-]+$"
jsonpath "$.fragment.ownerId" matches "^[0-9a-fA-F]+$"
jsonpath "$.fragment.created" isString
jsonpath "$.fragment.updated" isString
jsonpath "$.fragment.type" == "image/jpeg"
jsonpath "$.fragment.size" == 27929
[Captures]
url: header "Location"

# GET.ext By ID with converted type

GET {{url}}.png
Authorization: Basic dXNlcjFAZW1haWwuY29tOnBhc3N3b3JkMQ==

HTTP/1.1 200
Content-Type: image/png
[Asserts]
header "Content-Type" matches "image/png"

# GET.ext By ID with converted type

GET {{url}}.webp
Authorization: Basic dXNlcjFAZW1haWwuY29tOnBhc3N3b3JkMQ==

HTTP/1.1 200
Content-Type: image/webp
[Asserts]
header "Content-Type" matches "image/webp"


# GET.ext By ID with converted type

GET {{url}}.gif
Authorization: Basic dXNlcjFAZW1haWwuY29tOnBhc3N3b3JkMQ==

HTTP/1.1 200
Content-Type: image/gif
[Asserts]
header "Content-Type" matches "image/gif"

# GET By ID 

GET {{url}}
Authorization: Basic dXNlcjFAZW1haWwuY29tOnBhc3N3b3JkMQ==

HTTP/1.1 200
Content-Type: image/jpeg
[Asserts]
header "Content-Type" matches "image/jpeg"


